### PR TITLE
Fix/ld sidenav

### LINKED ISSUE #507: bug: sidenav does not collapse correctly
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://github.com/emdgroup-liquid/liquid/blob/main/CONTRIBUTING.md#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

@emdgroup-liquid/liquid@4.4.3

### Framework bindings

React

### Current behavior

The `<LdSidenav>` or its related `<LdSidenavToggleOutside>` component does not work correctly when using `collapseTrigger="mouseout"`. 

**Scenario 1**: not in narrow mode, moving the mouse (cursor) outside the sidenav area collapses the panel, but it cannot be re-opened using the button. The button also has a different colour than expected (it shows up as if `:focus` and `:focus-visible` both were active).

image

**Scenario 2**: in narrow mode, the collapse trigger works, unless one of the `<LdSidenavSubnav>` components contain a child that is not `<LdSidenavHeading>` or `<LdSidenavNavitem>`. For instance, having an `<LdTypo>` breaks the narrow mode completely, even though it has a parent that could be collapsed as described in the documentation (`<LdSidenavBack>`). It's not narrow anymore, and it cannot be re-opened by clicking on the button either (same as in Scenario 1)

Collapse with the button on the base level:
image

Expand and navigate to the subitem:
image

Move the cursor outside, or collapse the sidenav with the button:
image

**Scenario 3**: in narrow mode, the sidenav can be re-opened even if it has a different child (e.g. `<LdTypo>`) if the `collapseTrigger` is not applied, but the sidenav turns into its non-narrow mode on collapse even though it has an `<LdSidenavBack>` inside.

### Expected behavior

Scenario 1: after collapsing an `<LdSidenav>` in non-narrow mode using the `collapseTrigger`, I should be able to re-open it.

Scenario 2: after collapsing an `<LdSidenav>` in narrow mode using the `collapseTrigger` (either by pressing the button, or moving the cursor outside, but having that prop set), I should see a collapsed, narrow `<LdSidenav>` and should be able to re-open it.

Scenario 3: after collapsing an `<LdSidenav>` in narrow mode using the buttons, I should see a collapsed, narrow `<LdSidenav>`, not the non-narrow version.

### Steps to reproduce

1. Set up a React-based project (or use the provided sandbox from the documentation)
2. Update Liquid version to latest (`@emdgroup-liquid/liquid@4.4.3`)
3. Import and combine the necessary components to build a sidenav
    ```
    import {
      LdSidenav,
      LdSidenavBack,
      LdSidenavHeader,
      LdSidenavHeading,
      LdSidenavNavitem,
      LdSidenavSlider,
      LdSidenavSubnav,
      LdSidenavToggleOutside,
      LdTypo,
    } from '@emdgroup-liquid/liquid/dist/react'
    ```
4. Add `collapseTrigger="mouseout`
5. Check the behaviour
6. Add `narrow` to the sidenav
7. Replace one of the sub-navigation items with another component (e.g `<LdTypo>`)
8. Navigate to that sub-item
9. Check the behaviour
10. Remove `collapseTrigger="mouseout`
11. Navigate to the sub-navigation with another component
12. Collapse the sidenav

### Code reproduction URL

https://stackblitz.com/edit/github-ss8jru?file=src/components/Sidebar/Sidebar.tsx

### Additional information

In the sandbox, there's a `Sidebar` and a `SidebarNarrow` component prepared for testing. In the `SidebarNarrow`, the "Algorithms and data structures" menu item has the `<LdTypo>` inside.

The `App.tsx` includes both components, one is commented out.

### PR DESCRIPTION
**Pull request by borisdiakur**
# Description

This PR fixes three issues:
1. The `ld-toggle-outside` component doesn't work if the `ld-sidenav` has the `collapse-trigger` prop set to `mouseout`
2. The sidenav fully collapses, although it should collapse to narrow with either the back button or a slotted nav item still visible
3. The toggle outside element receiving focus on sidenav mouse out, when the sidenav itself is not an active element

Fixes #507

## Type of change

Please delete options that are not relevant.

- [x] Bugfix

## Is it a breaking change?

- [x] No

# How Has This Been Tested?

- [x] unit tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

File: src/liquid/components/ld-sidenav/ld-sidenav.tsx [hunk 1]
```diff
@@ -448,7 +449,20 @@ export class LdSidenav {
...
-  private activeSubnavContainsIcons = () => {
+  private activeSubnavContainsIconsOrHasBack = () => {
+    // Return true if we have a back button or a nav items as a direct child.
+    if (
+      Array.from(this.el.children).filter(
+        (child) =>
+          child.tagName === 'LD-SIDENAV-BACK' ||
+          (child.tagName === 'LD-SIDENAV-NAVITEM' &&
+            !(child as HTMLLdSidenavNavitemElement).mode)
+      ).length
```
Comment (toastedtoast) [inline src/liquid/components/ld-sidenav/ld-sidenav.tsx:460]: I kind of prefer to have an explicit boolean expression e.g.
```suggestion
      ).length > 0
```

File: src/liquid/components/ld-sidenav/ld-sidenav.tsx [hunk 2]
```diff
@@ -448,7 +449,20 @@ export class LdSidenav {
...
+    ) {
+      return true
+    }
```
Comment (toastedtoast) [inline src/liquid/components/ld-sidenav/ld-sidenav.tsx:463]: This whole filter expression is kind of hard to read especially directly as if condition.
Additionally it's kind of unfortunate that mode defaults to udefined although it is "basically" an enum which is omitting `primary` as the default value.

Anyways, I think to improve readability, how about extracting the filter to a variable.
```suggestion
    const backAndPrimaryNavItems = Array.from(this.el.children).filter(
        (child) =>
          child.tagName === 'LD-SIDENAV-BACK' ||
          (child.tagName === 'LD-SIDENAV-NAVITEM' &&
            !(child as HTMLLdSidenavNavitemElement).mode)
      )
    if (backAndPrimaryNavItems.length > 0){
      return true
    }
```

Sorry formatting does not work out well.

**Review by toastedtoast — APPROVED** [review]
Only requested a little change. Just style not mandatory. If you prefer the existing code I am also fine.
