### PR TITLE
fix(ld-select): wait for popper to be visible before focusing filter

### LINKED ISSUE #813: bug: LdSelect with filter doesn't always get focus
### Prerequisites

- [X] I know [how to contribute a proper bug report](https://liquid.merck.design/liquid/guides/contributing/#reporting-bugs).
- [X] I agree to follow the [Code of Conduct](https://github.com/emdgroup-liquid/liquid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/emdgroup-liquid/liquid/issues?q=is%3Aopen+is%3Aissue+label%3Abug) that already report this problem, without success.

### Liquid version

5.5.0

### Framework bindings

React

### Current behavior

Sometime, the focus is not done, and the bug can be observed when user clicks quickly on the LdSelect.

### Expected behavior

The focus should always be done.

### Steps to reproduce

Available sandbox on [CodeSandbox](https://codesandbox.io/p/github/dpitois/liquid-select-focus-bug/main?file=/README.md:1,1&workspaceId=bd142dc9-6e08-409c-9537-d407ff1d0ee3)

1. Click on the 1st LdSelect of the form
2. Click with different _speeds_ 
3. Focus may be done, or not
  a. Most of the time it is OK when `<ClickLogger />` has a duration above 50ms
  b. Maybe the focus is missing when the component displays a duration between 30 and 40ms

Note: the durations above are not accurate, sometime it works when being in the 30-40ms range, and sometime it does not work when above (like 130ms for example).

### Code reproduction URL

https://codesandbox.io/p/github/dpitois/liquid-select-focus-bug/main?file=/README.md:1,1&workspaceId=bd142dc9-6e08-409c-9537-d407ff1d0ee3

### Additional information

The provided repo and sandbox help to reproduce the bug based on the _click duration_, but in our implementation based on Custom Element and a React wrapped creating these elements, the bug is more easily reproduced.  
Because it is an internal project, it can not be shared in public, but if needed, we can try to get in touch with Merck internal tools like Teams to show the bug.

### PR DESCRIPTION
**Pull request by borisdiakur**
# Description

It looks like the Tether enable method returns before the actual popper element is visible. So we need to "wait" for it to become visible before setting the focus on the filter input element.

Fixes #813

## Type of change

- [x] Bugfix

## Is it a breaking change?

- [x] No

# How Has This Been Tested?

- [x] tested manually

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

File: src/liquid/components/ld-select/ld-select.tsx [hunk 1]
```diff
@@ -951,6 +951,16 @@ export class LdSelect implements InnerFocusable {
...
 
+  private focusFilterAsSoonAsVisible = (filterInput: HTMLInputElement) => {
+    setTimeout(() => {
+      if (this.listboxRef.style.display === 'none') {
+        this.focusFilterAsSoonAsVisible(filterInput)
+      } else {
+        filterInput.focus()
+      }
+    })
+  }
```
Comment (renet) [inline src/liquid/components/ld-select/ld-select.tsx:962]: This potentially results in very many calls of this iterative function. Maybe even something like a stack overflow, as this may run endlessly? Maybe adding a short debounce wrapper and limiting the amount of tries would be helpful?

And is there really no way to get notified as soon as rendering is done? 🙈

**Review by renet — CHANGES_REQUESTED** [review]

File: src/liquid/components/ld-select/ld-select.tsx (hunk 1 above)
Comment (dpitois) [reply src/liquid/components/ld-select/ld-select.tsx:962]: Don't know how it could be applied here, but maybe [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) can be used to listen to the style change?

Comment (borisdiakur) [reply src/liquid/components/ld-select/ld-select.tsx:962]: I have implemented a version using MutationObserver and it works well. However, it'll take some time for me to adjust all tests as we now need to mock MutationObserver logic for multiple observers and trigger their callbacks in the tests independently. I'm working on it.

**Review by renet — APPROVED** [review]
It's really a pity that Stencil doesn't have a better solution for this. 😢
